function socialBundle(row){try{const n=JSON.parse(row?.notes||'{}');if(n.kind==='social_package')return {posts:Number(n.posts||0),reels:Number(n.reels||0),stories:Number(n.stories||0)}}catch{}return null}
const n=v=>Number(v||0),today=()=>new Date().toISOString().slice(0,10);
function monthCountBetween(start,end){if(!start||!end||start>end)return 0;const sd=new Date(start+'T00:00:00'),ed=new Date(end+'T00:00:00');return Math.max(0,(ed.getFullYear()-sd.getFullYear())*12+ed.getMonth()-sd.getMonth()+1)}
function activeMonthsThisYear(start,end){const y=new Date().getFullYear(),ys=`${y}-01-01`,ye=`${y}-12-31`;let s=start&&start>ys?start:ys,e=end&&end<ye?end:ye;if(!s)s=ys;if(!e)e=ye;return monthCountBetween(s,e)}
function remainingMonthsThisYear(start,end){const now=new Date(),y=now.getFullYear(),current=`${y}-${String(now.getMonth()+1).padStart(2,'0')}-01`,ye=`${y}-12-31`;let s=start&&start>current?start:current,e=end&&end<ye?end:ye;if(!s)s=current;if(!e)e=ye;return monthCountBetween(s,e)}
export async function onRequestGet({env}){
  const db=env.DB;if(!db)return Response.json({error:'Binding D1 DB mancante'},{status:500});
  const [cr,sr,ir,pr,tr,cor,lr,er]=await db.batch([
    db.prepare(`SELECT * FROM clients ORDER BY CASE WHEN status='Attivo' THEN 0 ELSE 1 END,name`),
    db.prepare(`SELECT cs.*,s.name service_name FROM client_services cs LEFT JOIN services s ON s.id=cs.service_id`),
    db.prepare(`SELECT * FROM invoices`),db.prepare(`SELECT * FROM payments`),db.prepare(`SELECT * FROM transactions`),db.prepare(`SELECT * FROM contracts`),
    db.prepare(`SELECT COUNT(*) v FROM leads`),db.prepare(`SELECT COALESCE(SUM(purchase_cost),0) v FROM equipment`)
  ]);
  const clients=cr.results||[],services=sr.results||[],invoices=ir.results||[],payments=pr.results||[],transactions=tr.results||[],contracts=cor.results||[];
  const clientStats=clients.map(c=>{
    const cid=String(c.id),sv=services.filter(x=>String(x.client_id)===cid),social=socialBundle(sv.find(socialBundle))||{posts:0,reels:0,stories:0},inv=invoices.filter(x=>String(x.client_id)===cid),pp=payments.filter(x=>String(x.client_id)===cid),tx=transactions.filter(x=>String(x.client_id)===cid),ct=contracts.filter(x=>String(x.client_id)===cid&&x.end_date).sort((a,b)=>String(a.end_date).localeCompare(String(b.end_date)))[0];
    const income=tx.filter(x=>x.direction==='Entrata').reduce((s,x)=>s+n(x.amount),0),expense=tx.filter(x=>x.direction==='Uscita').reduce((s,x)=>s+n(x.amount),0),pkgStart=c.package_start_date||'',pkgEnd=c.package_end_date||'',months=activeMonthsThisYear(pkgStart,pkgEnd),remainingMonths=remainingMonthsThisYear(pkgStart,pkgEnd);
    const monthly=[];for(let i=11;i>=0;i--){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);const mk=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,mm=tx.filter(x=>String(x.date||'').slice(0,7)===mk);monthly.push({month:mk,revenue:mm.filter(x=>x.direction==='Entrata').reduce((s,x)=>s+n(x.amount),0),expense:mm.filter(x=>x.direction==='Uscita').reduce((s,x)=>s+n(x.amount),0)})}
    return {id:c.id,name:c.name,status:c.status,relationship_type:c.relationship_type||'',packageStart:pkgStart,packageEnd:pkgEnd,monthlyValue:n(c.monthly_value),annualRecurring:n(c.monthly_value)*months,remainingYearValue:n(c.monthly_value)*remainingMonths,fullYearValue:n(c.monthly_value)*12,invoiceIssued:inv.reduce((s,x)=>s+n(x.total),0),invoicePaid:inv.filter(x=>/pagata/i.test(x.status||'')).reduce((s,x)=>s+n(x.total),0),invoiceOutstanding:inv.filter(x=>!/pagata|annullata/i.test(x.status||'')).reduce((s,x)=>s+n(x.total),0),paymentsPaid:pp.filter(x=>/pagat/i.test(x.status||'')).reduce((s,x)=>s+n(x.amount),0),paymentsPending:pp.filter(x=>!/pagat|annull/i.test(x.status||'')).reduce((s,x)=>s+n(x.amount),0),overduePayments:pp.filter(x=>!/pagat|annull/i.test(x.status||'')&&x.due_date&&x.due_date<today()).reduce((s,x)=>s+n(x.amount),0),actualIncome:income,actualExpense:expense,netActual:income-expense,social:{...social,total:social.posts+social.reels+social.stories},contractEnd:ct?.end_date||'',services:sv.map(x=>x.custom_name||x.service_name||'Servizio').filter(Boolean),monthly};
  });
  const active=clients.filter(c=>c.status==='Attivo'),mrr=active.reduce((s,c)=>s+n(c.monthly_value),0),actualIncome=transactions.filter(x=>x.direction==='Entrata').reduce((s,x)=>s+n(x.amount),0),actualExpense=transactions.filter(x=>x.direction==='Uscita').reduce((s,x)=>s+n(x.amount),0),activeStats=clientStats.filter(x=>x.status==='Attivo');
  return Response.json({activeClients:active.length,totalClients:clients.length,mrr,annualProjection:activeStats.reduce((s,x)=>s+x.annualRecurring,0),remainingYearProjection:activeStats.reduce((s,x)=>s+x.remainingYearValue,0),actualIncome,actualExpense,actualNet:actualIncome-actualExpense,leads:Number(lr.results?.[0]?.v||0),equipmentValue:Number(er.results?.[0]?.v||0),clientStats});
}
